name: ai_economic_index

profile: ai_economic_index

model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  ai_economic_index:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
