select
    geo_id,
    geo_name,
    geography,
    date_start,
    date_end,
    platform_and_product,
    use_case,
    soc_group,
    replace(replace(soc_group, ' Occupations', ''), ' Occupation', '') as soc_group_display,
    mapped_task_count,
    work_use_case_count,
    work_use_case_pct,
    work_use_case_pct / 100 as work_use_case_share,
    task_success_observation_count,
    successful_task_count,
    task_success_rate,
    ai_autonomy_observation_count,
    ai_autonomy_score,
    ai_autonomy_score_ci_lower,
    ai_autonomy_score_ci_upper,
    human_only_time_observation_count,
    human_only_time_median,
    human_only_time_median_ci_lower,
    human_only_time_median_ci_upper,
    human_with_ai_time_observation_count,
    human_with_ai_time_median,
    human_with_ai_time_median_ci_lower,
    human_with_ai_time_median_ci_upper,
    time_savings_ratio,
    time_savings_ratio_ci_lower,
    time_savings_ratio_ci_upper,
    human_only_ability_observation_count,
    requires_ai_task_count,
    human_only_ability_requires_ai_rate,
    1 - human_only_ability_requires_ai_rate as human_only_rate
from `ai-economic-index.output_dataset.mart_aei_work_soc_outcomes`
where geo_id = 'GLOBAL'
  and use_case = 'work'
order by work_use_case_pct desc, soc_group_display