name: Deploy to GitHub Pages

on:
  push:
    branches: 'main' # or whichever branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: reports/package-lock.json
      
      - name: Install dependencies
        run: cd reports && npm install
      
      - name: build
        env:
          BASE_PATH: '/${{ github.event.repository.name }}'
          EVIDENCE_SOURCE__bq__authenticator: ${{ secrets.EVIDENCE_SOURCE__BQ__AUTHENTICATOR }}
          EVIDENCE_SOURCE__bq__client_email: ${{ secrets.EVIDENCE_SOURCE__BQ__CLIENT_EMAIL }}
          EVIDENCE_SOURCE__bq__enable_connected_sheets: ${{ secrets.EVIDENCE_SOURCE__BQ__ENABLE_CONNECTED_SHEETS }}
          EVIDENCE_SOURCE__bq__location: ${{ secrets.EVIDENCE_SOURCE__BQ__LOCATION }}
          EVIDENCE_SOURCE__bq__private_key: ${{ secrets.EVIDENCE_SOURCE__BQ__PRIVATE_KEY }}
          EVIDENCE_SOURCE__bq__project_id: ${{ secrets.EVIDENCE_SOURCE__BQ__PROJECT_ID }}
        run: |
          cd reports
          npm run sources
          npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'reports/build/${{ github.event.repository.name }}'

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
